kind: Service
apiVersion: v1
metadata:
  name: user
  namespace: srv
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      name: micro
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: srv
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        - name: user
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          command: [
            "service",
            "--selector=static",
            "--server_address=:8080",
          ]
          env:
            - name: APP_KEY
              value: "4RpKymtlXbizEQ8rOzHM3YybOrQuLya"
            - name: TOKEN_VALIDITY_PERIOD
              value: "15"
            - name: DB_HOST
              value: "user-mariadb"
            - name: DB_USER
              value: "user"
            - name: DB_NAME
              value: "user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mariadb-password
                  name: user-mariadb
          ports:
          - containerPort: 8080
            name: micro
            protocol: TCP
        - name: health
          image: microhq/health:kubernetes
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=user",
            "--server_address=0.0.0.0:8080"
          ]
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
