// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/casbin/casbin.proto

package casbin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Permission struct {
	Permission           []string `protobuf:"bytes,1,rep,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_f835afd114115d9e, []int{0}
}

func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetPermission() []string {
	if m != nil {
		return m.Permission
	}
	return nil
}

type Request struct {
	Role                 string        `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	User                 string        `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Permission           string        `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f835afd114115d9e, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Request) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Request) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

func (m *Request) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type Response struct {
	Valid                bool          `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Role                 string        `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	User                 string        `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Permission           *Permission   `protobuf:"bytes,4,opt,name=permission,proto3" json:"permission,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f835afd114115d9e, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Response) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Response) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Response) GetPermission() *Permission {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *Response) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*Permission)(nil), "casbin.Permission")
	proto.RegisterType((*Request)(nil), "casbin.Request")
	proto.RegisterType((*Response)(nil), "casbin.Response")
}

func init() { proto.RegisterFile("proto/casbin/casbin.proto", fileDescriptor_f835afd114115d9e) }

var fileDescriptor_f835afd114115d9e = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4e, 0x2c, 0x4e, 0xca, 0xcc, 0x83, 0x52, 0x7a, 0x60, 0x31, 0x21, 0x36, 0x08,
	0x4f, 0x49, 0x87, 0x8b, 0x2b, 0x20, 0xb5, 0x28, 0x37, 0xb3, 0xb8, 0x38, 0x33, 0x3f, 0x4f, 0x48,
	0x8e, 0x8b, 0xab, 0x00, 0xce, 0x93, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0c, 0x42, 0x12, 0x51, 0x6a,
	0x67, 0xe4, 0x62, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0x29, 0xca,
	0xcf, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0xa5, 0xc5, 0xa9,
	0x45, 0x12, 0x4c, 0x10, 0x31, 0x10, 0x1b, 0xcd, 0x4c, 0x66, 0xb0, 0x0c, 0x92, 0x88, 0x90, 0x09,
	0x17, 0x37, 0x82, 0x57, 0x2c, 0xc1, 0xa2, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa4, 0x07, 0x75, 0x2d,
	0xc2, 0x71, 0x41, 0xc8, 0xca, 0x94, 0x36, 0x31, 0x72, 0x71, 0x04, 0xa5, 0x16, 0x17, 0xe4, 0xe7,
	0x15, 0xa7, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x64, 0xa6, 0x80, 0xdd, 0xc2, 0x11, 0x04,
	0xe1, 0xc0, 0x1d, 0xc8, 0x84, 0xc5, 0x81, 0xcc, 0x48, 0x0e, 0x34, 0x42, 0x71, 0x20, 0x8b, 0x02,
	0x23, 0x0e, 0xfb, 0xf1, 0x38, 0x9a, 0x95, 0x28, 0x47, 0x1b, 0x6d, 0x60, 0xe4, 0x62, 0x73, 0x06,
	0x2b, 0x11, 0x32, 0xe5, 0xe2, 0x73, 0x4c, 0x49, 0x41, 0x28, 0x2c, 0x16, 0xe2, 0x87, 0xe9, 0x86,
	0x06, 0xb0, 0x94, 0x00, 0x42, 0x00, 0xe2, 0x4f, 0x25, 0x06, 0x21, 0x0b, 0x2e, 0x41, 0x97, 0xd4,
	0x9c, 0xd4, 0x92, 0x54, 0x92, 0x75, 0x9a, 0x72, 0xf1, 0xb9, 0xa7, 0x96, 0x90, 0xaa, 0x2d, 0x89,
	0x0d, 0x9c, 0x5c, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x5c, 0x1e, 0x3a, 0x4b, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Casbin service

type CasbinClient interface {
	// 全部权限
	AddPermissions(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	DeletePermissions(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetPermissions(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type casbinClient struct {
	c           client.Client
	serviceName string
}

func NewCasbinClient(serviceName string, c client.Client) CasbinClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "casbin"
	}
	return &casbinClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *casbinClient) AddPermissions(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Casbin.AddPermissions", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *casbinClient) DeletePermissions(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Casbin.DeletePermissions", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *casbinClient) GetPermissions(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Casbin.GetPermissions", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Casbin service

type CasbinHandler interface {
	// 全部权限
	AddPermissions(context.Context, *Request, *Response) error
	DeletePermissions(context.Context, *Request, *Response) error
	GetPermissions(context.Context, *Request, *Response) error
}

func RegisterCasbinHandler(s server.Server, hdlr CasbinHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Casbin{hdlr}, opts...))
}

type Casbin struct {
	CasbinHandler
}

func (h *Casbin) AddPermissions(ctx context.Context, in *Request, out *Response) error {
	return h.CasbinHandler.AddPermissions(ctx, in, out)
}

func (h *Casbin) DeletePermissions(ctx context.Context, in *Request, out *Response) error {
	return h.CasbinHandler.DeletePermissions(ctx, in, out)
}

func (h *Casbin) GetPermissions(ctx context.Context, in *Request, out *Response) error {
	return h.CasbinHandler.GetPermissions(ctx, in, out)
}
